name: GitHub Classroom Workflow

on: 
  - push
  - workflow_dispatch

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"
      - name: Install dependencies
        run: |
          python -m pip install --quiet --upgrade pip
          pip install --quiet -r requirements.txt
      - name: Generate problems
        uses: tatsy-classes/sudoku-autograding@main
      - name: Autograding
        uses: education/autograding@v1
